library(devtools)
library(tidyverse)
library(fs)

###create_package("~/Projects/R_packages/scDNA")
use_git()
use_mit_license("Bobby Bowman")

setwd("~/Projects/R_packages/scDNA")

use_r("read_tapestri_h5_NGT")
use_r("quality_filter_NGT")
use_r("quality_output")
use_r("annotate_variants")
use_r("TI_mimic_filter")
use_r("active_NGT_filter")
use_r("generate_lowQC_matrix")
use_r("enumerate_clones")
use_r("clonograph")
use_r("clone_QC")
use_r("select_clones")
use_r("read_tapestri_h5_protein")
use_r("extract_droplet_size")
use_r("normalize_protein_data")
use_r("variant_ID")
use_r("tapestri_h5_to_sce")
use_r("BuildMDP")
use_r("attach_weights")
use_r("mdp_Q_learning_with_linklist")
use_r("trajectory_analysis")
use_r("get_own_path")
use_r("VisualizeMDPs")
use_r("generate_txdb")
use_r("compute_clone_statistics")
use_r("fcs_export")
use_r("readDNA_CN_H5")
use_r("optimize_AF_mat")
use_readme_rmd()
use_devtools()

load_all()
document()
check()
build()

usethis::use_version("patch")

use_package("AnnotationDbi")
use_package("Homo.sapiens")
use_package("cowplot")
use_package("GenomicFeatures")
use_package("Matrix")
use_package("RColorBrewer")
use_package("flowCore")
use_package("Seurat",type = "Suggests")
use_package("SingleCellExperiment",type = "Imports")
use_package("SummarizedExperiment",type = "Imports")
use_package("doParallel",type = "Imports")
use_package("foreach",type = "Imports")
use_package("mefa4",type = "Imports")
use_package("stringr",type = "Imports")
use_package("tibble",type = "Imports")
use_package("vegan",type = "Imports")

